# Test this workflow with
# act create -W ./.github/workflows/on-create.yml
name: On Create
on:
  create:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - # Contexts
        # https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts
        run: echo ${{ github.sha }}
      - # Default environment variables
        # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
        run: echo ${GITHUB_SHA:0:7}
      - run: echo ${GITHUB_ACTIONS}
      - run: echo ${GITHUB_REF_NAME}
  db:
    runs-on: ubuntu-latest
    env:
      DB_URL: postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}
    steps:
      - # Install `psql`
        # https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-actions-workflow
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      # - # query the db
      #    run: psql $DB_URL -c "SELECT datname FROM pg_database"
      - # set env DB_NAME
        # 1. replace dash (-) & forward slash (/) with underscore (_)
        # 2. truncate to first 15 chars
        # 3. prefix with "git_"
        name: Set DB_NAME env var
        run: |
          echo "DB_NAME=git_$(echo $GITHUB_REF_NAME | sed -r 's/[-/]+/_/g'| cut -c 1-15)" >> $GITHUB_ENV
          echo ${DB_NAME}
      - # create a database
        name: Create Database
        # GITHUB_REF_NAME is not available in `act`
        run: psql $DB_URL -c "CREATE DATABASE ${DB_NAME}"
